# Generated by Django 5.0.3 on 2024-04-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_chatmessage_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificactivity',
            name='conference_participation',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.scientificactivity'),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='citation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Citation Count'),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='impact_factor',
            field=models.FloatField(default=0, verbose_name='Impact Factor'),
        ),
    ]
