# Generated by Django 5.0.3 on 2024-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_user_permissions'),
        ('main_page', '0007_publicationtype_remove_notification_related_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publication_authors', through='main_page.Author', to='accounts.user'),
        ),
    ]
