# Generated by Django 5.0.3 on 2024-04-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_publication_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
